(()=>{
const KEY='oshiCategoryAxes';let axes=JSON.parse(localStorage.getItem(KEY)||'[]');
const escCat=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function saveAxes(){localStorage.setItem(KEY,JSON.stringify(axes))}
function axisById(id){return axes.find(a=>String(a.id)===String(id))}
function selectedNow(){const out={};document.querySelectorAll('.categoryChoice:checked').forEach(e=>(out[e.dataset.axis]||(out[e.dataset.axis]=[])).push(e.value));return out}
function renderAssignments(sel={}){const c=document.getElementById('categoryAssignments');if(!c)return;if(!axes.length){c.innerHTML='<div class="categoryEmpty">まだカテゴリなし。下のボタンから作れるっしょ。</div>';return}c.innerHTML=axes.map(a=>`<div class="categoryAssign"><b>${escCat(a.name)}</b><div class="choiceGrid">${a.options.map(o=>`<label class="choiceLabel"><input class="categoryChoice" type="checkbox" data-axis="${a.id}" value="${o.id}" ${(sel[a.id]||[]).map(String).includes(String(o.id))?'checked':''}>${escCat(o.name)}</label>`).join('')}</div></div>`).join('')}
window.createCategoryAxis=function(){const keep=selectedNow(),name=prompt('カテゴリの分類名\n例：推し方');if(!name||!name.trim())return;const raw=prompt('項目を「、」区切りで入力\n例：現場行く推し、ただ愛でたい推し');const id='a'+Date.now(),opts=[...new Set((raw||'').split(/[、,\n]/).map(x=>x.trim()).filter(Boolean))];axes.push({id,name:name.trim(),options:opts.map((n,i)=>({id:id+'o'+i,name:n}))});saveAxes();renderAssignments(keep);if(document.getElementById('listScreen')?.classList.contains('active'))renderList()}
window.setCategoryGrouping=function(v){appSettings.listGroupAxis=v;saveSettings();renderList()}
const style=document.createElement('style');style.textContent=`.listTools{display:flex;gap:8px;margin:2px 0 12px}.listTools select{flex:1;min-width:0;border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:13px;padding:9px}.categoryBtn{border:1px solid var(--line);background:#fff;border-radius:13px;padding:9px 11px;font-weight:800;white-space:nowrap}.groupHead{font-size:calc(17px * var(--font-scale));font-weight:900;margin:16px 3px 7px}.groupHead small{color:var(--muted);font-size:calc(11px * var(--font-scale));font-weight:600}.categoryAssign{margin:9px 0;padding:11px;border:1px solid var(--line);border-radius:14px;background:#fff}.categoryAssign b{display:block;margin-bottom:7px}.choiceGrid{display:flex;flex-wrap:wrap;gap:6px}.choiceLabel{display:inline-flex;gap:5px;align-items:center;padding:6px 8px;border:1px solid var(--line);border-radius:999px;font-size:calc(11px * var(--font-scale))}.choiceLabel input{width:auto}.categoryEmpty{padding:12px;border:1px dashed var(--line);border-radius:14px;color:var(--muted);font-size:calc(11px * var(--font-scale))}`;document.head.appendChild(style);
const profileStyle=document.querySelector('.profileStyleCard');if(profileStyle){const box=document.createElement('div');box.className='field';box.innerHTML='<label>カテゴリ <span class="optional">任意・複数可</span></label><div id="categoryAssignments"></div><button type="button" class="secondary" onclick="createCategoryAxis()">＋ カテゴリを作る</button>';profileStyle.before(box)}
const baseBlank=window.blankForm;baseBlank&&(window.blankForm=function(){baseBlank();renderAssignments({})});
const baseFill=window.fillForm;baseFill&&(window.fillForm=function(o){baseFill(o);renderAssignments(o.categoryAssignments||{})});
const baseGet=window.getFormData;baseGet&&(window.getFormData=function(id){const o=baseGet(id);o.categoryAssignments=selectedNow();return o});
function card(o){return `<div class="card"><button class="oshiCardBtn" onclick="openDetail(${o.id})"><div class="oshiRow"><div class="avatar" style="border-color:${o.color}">${o.icon?`<img src="${o.icon}">`:escCat(o.name.slice(0,2))}</div><div class="oshiText"><div class="oshiName">${escCat(o.name)}</div><div class="meta">${escCat([o.group,o.category,o.agency].filter(Boolean).slice(0,2).join(' / ')||'詳細未設定')}</div><div class="colorline"><span class="dot" style="background:${o.color}"></span><span>${escCat(o.colorName||'カラー名未設定')}</span>${o.startDate?`<span>・${countDays(o)}日</span>`:''}</div></div><div class="chev">›</div></div></button></div>`}
window.renderList=function(){const c=document.getElementById('listContent'),axis=axisById(appSettings.listGroupAxis||'');if(!c)return;const tools=`<div class="listTools"><select onchange="setCategoryGrouping(this.value)"><option value="">グループ分け：なし</option>${axes.map(a=>`<option value="${a.id}" ${axis&&String(axis.id)===String(a.id)?'selected':''}>グループ分け：${escCat(a.name)}</option>`).join('')}</select><button class="categoryBtn" onclick="createCategoryAxis()">＋カテゴリ</button></div>`;if(!oshis.length){c.innerHTML=tools+'<div class="empty"><div><div class="emptyIcon">💗</div><h2>まだ推しがいません</h2><p class="hint">まず1人登録してみるっしょ。</p><button class="primary" onclick="openForm()">＋ 推しを登録する</button></div></div>';return}if(!axis){c.innerHTML=tools+'<div class="sub" style="margin:3px 3px 10px">登録中の推し・'+oshis.length+'</div>'+oshis.map(card).join('');return}let html=tools;axis.options.forEach(op=>{const members=oshis.filter(o=>(o.categoryAssignments?.[axis.id]||[]).map(String).includes(String(op.id)));if(members.length)html+=`<div class="groupHead">${escCat(op.name)} <small>${members.length}人</small></div>${members.map(card).join('')}`});const unc=oshis.filter(o=>!(o.categoryAssignments?.[axis.id]||[]).length);if(unc.length)html+=`<div class="groupHead">未分類 <small>${unc.length}人</small></div>${unc.map(card).join('')}`;c.innerHTML=html};
setTimeout(()=>{if(document.getElementById('listScreen')?.classList.contains('active'))renderList()},0);
})();
