(()=>{
const escF=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function installFields(){const form=document.querySelector('#formScreen form')||document.querySelector('#formScreen');if(!form||document.getElementById('fanMark'))return;const actions=form.querySelector('.actions');if(!actions)return;const wrap=document.createElement('div');wrap.id='favoriteFanFields';wrap.innerHTML=`<div class="field"><label>ファンマーク・絵文字 <span class="optional">任意</span></label><input id="fanMark" type="text" placeholder="例：🐟💚 / 💜🧸☪️ / 👼🏻🐈‍⬛" autocomplete="off"><div class="hint fanHint">公式ファンマークや検索避けに使う絵文字など、好きな並びで登録できるっしょ。</div></div><div class="toggleRow favoriteRow"><div><b>♥ お気に入り</b><div class="sub">一覧ではお気に入りの推しを優先して上に表示</div></div><label class="switch"><input id="favoriteOshi" type="checkbox"><span class="slider"></span></label></div>`;actions.parentNode.insertBefore(wrap,actions)}
function current(){return typeof editingId!=='undefined'&&editingId!=null?oshis.find(o=>String(o.id)===String(editingId)):null}
function fill(){installFields();const o=current();const f=document.getElementById('fanMark'),fav=document.getElementById('favoriteOshi');if(f)f.value=o?.fanMark||'';if(fav)fav.checked=!!o?.favorite}
function saveInto(){const o=current();if(!o)return;o.fanMark=(document.getElementById('fanMark')?.value||'').trim();o.favorite=!!document.getElementById('favoriteOshi')?.checked;localStorage.setItem('oshiPrototypeData',JSON.stringify(oshis))}
const oldOpen=window.openForm;if(typeof oldOpen==='function')window.openForm=function(...args){const r=oldOpen.apply(this,args);setTimeout(fill,0);return r};
// Save button/form handler runs first; capture the entered values and attach them to the saved record just after base save.
document.addEventListener('click',e=>{const btn=e.target.closest('#formScreen .primary');if(!btn)return;const fan=(document.getElementById('fanMark')?.value||'').trim(),fav=!!document.getElementById('favoriteOshi')?.checked;setTimeout(()=>{let o=current();if(!o&&oshis.length)o=oshis[oshis.length-1];if(!o)return;o.fanMark=fan;o.favorite=fav;localStorage.setItem('oshiPrototypeData',JSON.stringify(oshis));if(typeof renderList==='function'&&document.getElementById('listScreen')?.classList.contains('active'))renderList()},0)},true);
installFields();
const st=document.createElement('style');st.textContent=`.fanHint{margin:6px 1px 0}.favoriteRow{margin:4px 0 12px;padding:12px 2px}.favoriteRow .sub{margin-top:3px}`;document.head.appendChild(st);
})();