(()=>{
const DATA_KEY='oshiPrototypeData';
const ACTIVE_KEY='oshiHomeActiveOshiId';
const SETTINGS_KEY='oshiHomeSettingsByOshi';
const $=id=>document.getElementById(id);
const mediaDraft={bg:null,oshi:null,fan:null,removeBg:false,removeOshi:false,removeFan:false};
function list(){try{const v=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function active(){const a=list(),id=localStorage.getItem(ACTIVE_KEY);return (id&&a.find(o=>String(o.id)===String(id)))||a.find(o=>o.favorite)||a[0]||null}
function allSettings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{return{}}}
function readData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error||new Error('read failed'));r.readAsDataURL(file)})}
async function fileValue(id,kind){const f=$(id)?.files?.[0];if(!f)return null;if(kind==='video'){if(f.size>1500000)throw new Error('動画が大きすぎるっしょ。試作版では1.5MB以下の動画で試してね。');return await readData(f)}return null}
function resetDraft(){mediaDraft.bg=null;mediaDraft.oshi=null;mediaDraft.fan=null;mediaDraft.removeBg=false;mediaDraft.removeOshi=false;mediaDraft.removeFan=false}
function ensureCropper(){if($('hv2Cropper'))return;const m=document.createElement('div');m.id='hv2Cropper';m.className='hv2-cropper';m.innerHTML=`<div class="hv2-crop-panel"><div class="hv2-crop-head"><b id="hv2CropTitle">画像を調整</b><button type="button" id="hv2CropCancel">×</button></div><div class="hv2-canvas-wrap"><canvas id="hv2CropCanvas"></canvas></div><label class="hv2-zoom">拡大<input id="hv2CropZoom" type="range" min="1" max="3" step="0.01" value="1"></label><div class="hv2-crop-help">画像を指で動かして位置を調整</div><button type="button" id="hv2CropDone">この位置で決定</button></div>`;document.body.appendChild(m);$('hv2CropCancel').onclick=()=>m.classList.remove('open')}
function openCropper(file,kind){ensureCropper();return new Promise((resolve,reject)=>{const m=$('hv2Cropper'),canvas=$('hv2CropCanvas'),ctx=canvas.getContext('2d'),zoom=$('hv2CropZoom');const isBg=kind==='bg';canvas.width=isBg?540:420;canvas.height=isBg?960:420;$('hv2CropTitle').textContent=isBg?'ホーム背景をトリミング':'アイコンをトリミング';zoom.value='1';const url=URL.createObjectURL(file),img=new Image();let scale=1,base=1,ox=0,oy=0,drag=false,lastX=0,lastY=0;
function clamp(){const w=img.naturalWidth*base*scale,h=img.naturalHeight*base*scale;const minX=canvas.width-w,maxX=0,minY=canvas.height-h,maxY=0;ox=Math.min(maxX,Math.max(minX,ox));oy=Math.min(maxY,Math.max(minY,oy))}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);clamp();ctx.drawImage(img,ox,oy,img.naturalWidth*base*scale,img.naturalHeight*base*scale)}
img.onload=()=>{base=Math.max(canvas.width/img.naturalWidth,canvas.height/img.naturalHeight);const w=img.naturalWidth*base,h=img.naturalHeight*base;ox=(canvas.width-w)/2;oy=(canvas.height-h)/2;draw();m.classList.add('open')};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('画像を開けなかったっしょ'))};
zoom.oninput=()=>{const old=scale;scale=Number(zoom.value);const cx=canvas.width/2,cy=canvas.height/2;ox=cx-(cx-ox)*(scale/old);oy=cy-(cy-oy)*(scale/old);draw()};
canvas.onpointerdown=e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const rect=canvas.getBoundingClientRect(),sx=canvas.width/rect.width,sy=canvas.height/rect.height;ox+=(e.clientX-lastX)*sx;oy+=(e.clientY-lastY)*sy;lastX=e.clientX;lastY=e.clientY;draw()};canvas.onpointerup=canvas.onpointercancel=()=>drag=false;
$('hv2CropDone').onclick=()=>{try{draw();const quality=isBg?.82:.88;const data=canvas.toDataURL('image/jpeg',quality);m.classList.remove('open');URL.revokeObjectURL(url);resolve(data)}catch(e){reject(e)}};$('hv2CropCancel').onclick=()=>{m.classList.remove('open');URL.revokeObjectURL(url);resolve(null)} })}
function addMediaTools(){const modal=$('hv2EditModal');if(!modal||modal.dataset.mediaTools==='1')return;modal.dataset.mediaTools='1';resetDraft();const specs=[['hv2BgImage','背景画像','bg'],['hv2OshiIcon','推しアイコン','oshi'],['hv2FanIcon','オタクのアイコン','fan']];for(const [id,label,kind] of specs){const input=$(id);if(!input)continue;const row=document.createElement('div');row.className='hv2-media-actions';row.innerHTML=`<button type="button" data-crop-status="${kind}">未変更</button><button type="button" class="danger" data-remove-media="${kind}">選択を削除</button>`;input.parentElement.appendChild(row);input.addEventListener('change',async()=>{const f=input.files?.[0];if(!f)return;try{const data=await openCropper(f,kind==='bg'?'bg':'icon');if(!data){input.value='';return}mediaDraft[kind]=data;mediaDraft['remove'+kind.charAt(0).toUpperCase()+kind.slice(1)]=false;row.querySelector(`[data-crop-status="${kind}"]`).textContent='トリミング済み ✓'}catch(e){alert(e?.message||'トリミングできなかったっしょ');input.value=''}})}
modal.querySelectorAll('[data-remove-media]').forEach(btn=>btn.onclick=()=>{const kind=btn.dataset.removeMedia;if(kind==='bg'){mediaDraft.bg=null;mediaDraft.removeBg=true;$('hv2BgImage')&&($('hv2BgImage').value='');$('hv2BgVideo')&&($('hv2BgVideo').value='')}if(kind==='oshi'){mediaDraft.oshi=null;mediaDraft.removeOshi=true;$('hv2OshiIcon')&&($('hv2OshiIcon').value='')}if(kind==='fan'){mediaDraft.fan=null;mediaDraft.removeFan=true;$('hv2FanIcon')&&($('hv2FanIcon').value='')}modal.querySelector(`[data-crop-status="${kind}"]`).textContent='削除予定'});
}
async function saveHomeFromForm(btn){const o=active();if(!o)throw new Error('推しが見つからないっしょ');const all=allSettings(),old=all[String(o.id)]||{};const s={...old};s.oshiName=$('hv2OshiName')?.value.trim()||o.name||'';s.fanName=$('hv2FanName')?.value.trim()||'わたし';s.phrase=$('hv2Phrase')?.value.trim()||'好きになって';s.startDate=$('hv2StartDate')?.value||o.startDate||'';s.showDays=!!$('hv2ShowDays')?.checked;s.showYmd=!!$('hv2ShowYmd')?.checked;s.showBirthday=!!$('hv2ShowBirthday')?.checked;s.textColor=$('hv2TextColor')?.value||'#ffffff';s.overlay=Number($('hv2Overlay')?.value||36);
const bgVideo=await fileValue('hv2BgVideo','video');
if(mediaDraft.removeBg){delete s.backgroundType;delete s.backgroundData}else if(mediaDraft.bg){s.backgroundType='image';s.backgroundData=mediaDraft.bg}else if(bgVideo){s.backgroundType='video';s.backgroundData=bgVideo}
if(mediaDraft.removeOshi)delete s.oshiIcon;else if(mediaDraft.oshi)s.oshiIcon=mediaDraft.oshi;
if(mediaDraft.removeFan)delete s.fanIcon;else if(mediaDraft.fan)s.fanIcon=mediaDraft.fan;
all[String(o.id)]=s;try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(all))}catch(e){throw new Error('画像の保存容量を超えたっしょ。別の画像か小さめの画像で試してね。')}
if(btn){btn.textContent='保存した！';btn.disabled=true}setTimeout(()=>{document.getElementById('hv2EditModal')?.classList.remove('open');resetDraft();if(typeof window.renderHome==='function')window.renderHome()},180)}
const style=document.createElement('style');style.textContent=`#homeScreen>.homeTop{display:none!important}#homeScreen>.homeTop+#homeBody{margin-top:0!important}.hv2-modal{z-index:500!important}.hv2-save{position:relative;z-index:2;touch-action:manipulation}.hv2-media-actions{display:flex;gap:8px;margin-top:8px}.hv2-media-actions button{border:1px solid #e9e0e5;background:#fff;border-radius:12px;padding:8px 10px;font:inherit}.hv2-media-actions button:first-child{color:#777;pointer-events:none}.hv2-media-actions .danger{color:#d34b5b}.hv2-cropper{position:fixed;inset:0;z-index:900;background:rgba(0,0,0,.72);display:none;align-items:flex-end}.hv2-cropper.open{display:flex}.hv2-crop-panel{width:min(520px,100%);margin:auto;background:#fff;border-radius:24px 24px 0 0;padding:14px 14px calc(20px + env(safe-area-inset-bottom));color:#262227}.hv2-crop-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.hv2-crop-head button{border:0;background:#f3f0f2;border-radius:12px;width:36px;height:36px;font-size:22px}.hv2-canvas-wrap{width:100%;max-height:58dvh;display:grid;place-items:center;background:#111;border-radius:16px;overflow:hidden}.hv2-canvas-wrap canvas{display:block;max-width:100%;max-height:58dvh;touch-action:none}.hv2-zoom{display:flex;gap:10px;align-items:center;margin:12px 2px 6px}.hv2-zoom input{flex:1}.hv2-crop-help{text-align:center;color:#8f858d;font-size:12px;margin:5px 0 10px}.hv2-crop-panel>button:last-child{width:100%;border:0;border-radius:15px;background:#262227;color:#fff;padding:13px;font-weight:800}`;document.head.appendChild(style);
const obs=new MutationObserver(()=>addMediaTools());obs.observe(document.documentElement,{subtree:true,childList:true});
document.addEventListener('click',async e=>{const btn=e.target.closest?.('#hv2Save');if(!btn)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(btn.disabled)return;const original=btn.textContent;btn.textContent='保存中…';try{await saveHomeFromForm(btn)}catch(err){console.error(err);btn.textContent=original;btn.disabled=false;alert(err?.message||'保存できなかったっしょ')}} ,true);
})();