(()=>{
const DATA_KEY='oshiPrototypeData',ACTIVE_KEY='oshiHomeActiveOshiId',SETTINGS_KEY='oshiHomeSettingsByOshi';
const $=id=>document.getElementById(id);let draft={bg:null,oshi:null,fan:null,removeBg:false,removeOshi:false,removeFan:false};
function list(){try{const v=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function active(){const a=list(),id=localStorage.getItem(ACTIVE_KEY);return(id&&a.find(o=>String(o.id)===String(id)))||a.find(o=>o.favorite)||a[0]||null}
function all(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{return{}}}
function reset(){draft={bg:null,oshi:null,fan:null,removeBg:false,removeOshi:false,removeFan:false}}
function crop(file,kind){return new Promise(resolve=>{let m=$('hv2Cropper');if(!m){m=document.createElement('div');m.id='hv2Cropper';m.className='hv2-cropper';document.body.appendChild(m)}m.innerHTML=`<div class="hv2-crop-panel"><div class="hv2-crop-head"><b>${kind==='bg'?'背景をトリミング':'アイコンをトリミング'}</b><button type="button" data-cancel>×</button></div><div class="hv2-canvas-wrap"><canvas id="hv2CropCanvas"></canvas></div><label class="hv2-zoom">拡大・縮小<input id="hv2CropZoom" type="range" min="1" max="4" step=".01" value="1"></label><div class="hv2-crop-help">画像を指で動かして位置を調整</div><button type="button" id="hv2CropDone">この位置で決定</button></div>`;const c=$('hv2CropCanvas'),ctx=c.getContext('2d'),z=$('hv2CropZoom'),bg=kind==='bg';c.width=bg?540:480;c.height=bg?960:480;const url=URL.createObjectURL(file),img=new Image();let base=1,scale=1,x=0,y=0,drag=false,lx=0,ly=0;
const clamp=()=>{const w=img.naturalWidth*base*scale,h=img.naturalHeight*base*scale;x=Math.min(0,Math.max(c.width-w,x));y=Math.min(0,Math.max(c.height-h,y))};const draw=()=>{clamp();ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,x,y,img.naturalWidth*base*scale,img.naturalHeight*base*scale)};
img.onload=()=>{base=Math.max(c.width/img.naturalWidth,c.height/img.naturalHeight);x=(c.width-img.naturalWidth*base)/2;y=(c.height-img.naturalHeight*base)/2;draw();m.classList.add('open')};img.src=url;z.oninput=()=>{const old=scale;scale=+z.value;const cx=c.width/2,cy=c.height/2;x=cx-(cx-x)*scale/old;y=cy-(cy-y)*scale/old;draw()};c.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture?.(e.pointerId)};c.onpointermove=e=>{if(!drag)return;const r=c.getBoundingClientRect();x+=(e.clientX-lx)*c.width/r.width;y+=(e.clientY-ly)*c.height/r.height;lx=e.clientX;ly=e.clientY;draw()};c.onpointerup=c.onpointercancel=()=>drag=false;
const finish=v=>{m.classList.remove('open');URL.revokeObjectURL(url);resolve(v)};m.querySelector('[data-cancel]').onclick=()=>finish(null);$('hv2CropDone').onclick=()=>finish(c.toDataURL('image/jpeg',bg?.76:.82))})}
function install(){const m=$('hv2EditModal');if(!m||!m.classList.contains('open')||m.dataset.cropReady==='1')return;m.dataset.cropReady='1';reset();[['hv2BgImage','bg'],['hv2OshiIcon','oshi'],['hv2FanIcon','fan']].forEach(([id,k])=>{const inp=$(id);if(!inp)return;const box=document.createElement('div');box.className='hv2-media-actions';box.innerHTML=`<span data-state>変更なし</span><button type="button" data-remove>画像を削除</button>`;inp.parentElement.appendChild(box);inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;const data=await crop(f,k);if(!data){inp.value='';return}draft[k]=data;draft['remove'+k[0].toUpperCase()+k.slice(1)]=false;box.querySelector('[data-state]').textContent='トリミング済み ✓'};box.querySelector('[data-remove]').onclick=()=>{draft[k]=null;draft['remove'+k[0].toUpperCase()+k.slice(1)]=true;inp.value='';box.querySelector('[data-state]').textContent='削除予定'}})}
async function video(){const f=$('hv2BgVideo')?.files?.[0];if(!f)return null;if(f.size>1500000)throw Error('動画が大きすぎるっしょ。試作版では1.5MB以下で試してね。');return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=rej;r.readAsDataURL(f)})}
async function save(){const o=active();if(!o)return;const a=all(),s={...(a[String(o.id)]||{})};s.oshiName=$('hv2OshiName')?.value.trim()||o.name||'';s.fanName=$('hv2FanName')?.value.trim()||'わたし';s.phrase=$('hv2Phrase')?.value.trim()||'好きになって';s.startDate=$('hv2StartDate')?.value||o.startDate||'';s.showDays=!!$('hv2ShowDays')?.checked;s.showYmd=!!$('hv2ShowYmd')?.checked;s.showBirthday=!!$('hv2ShowBirthday')?.checked;s.textColor=$('hv2TextColor')?.value||'#fff';s.overlay=+$('hv2Overlay')?.value||36;const v=await video();if(draft.removeBg){s.backgroundData='';s.backgroundType='image'}else if(draft.bg){s.backgroundData=draft.bg;s.backgroundType='image'}else if(v){s.backgroundData=v;s.backgroundType='video'}if(draft.removeOshi)s.oshiIcon='';else if(draft.oshi)s.oshiIcon=draft.oshi;if(draft.removeFan)s.fanIcon='';else if(draft.fan)s.fanIcon=draft.fan;a[String(o.id)]=s;localStorage.setItem(SETTINGS_KEY,JSON.stringify(a));$('hv2EditModal')?.classList.remove('open');reset();window.renderHome?.()}
const st=document.createElement('style');st.textContent=`.hv2-media-actions{display:flex;align-items:center;gap:10px;margin:7px 0 12px}.hv2-media-actions span{font-size:12px;color:#888}.hv2-media-actions button{border:1px solid #eadfe5;background:#fff;color:#d34b5b;border-radius:12px;padding:7px 10px}.hv2-cropper{position:fixed;inset:0;z-index:9999;background:#000b;display:none;align-items:flex-end}.hv2-cropper.open{display:flex}.hv2-crop-panel{width:min(520px,100%);margin:auto;background:#fff;padding:14px 14px calc(18px + env(safe-area-inset-bottom));border-radius:24px 24px 0 0;color:#222}.hv2-crop-head{display:flex;justify-content:space-between;align-items:center}.hv2-crop-head button{border:0;border-radius:12px;width:38px;height:38px;font-size:22px}.hv2-canvas-wrap{margin-top:10px;background:#111;border-radius:16px;overflow:hidden;display:grid;place-items:center;max-height:58dvh}.hv2-canvas-wrap canvas{max-width:100%;max-height:58dvh;touch-action:none}.hv2-zoom{display:flex;gap:10px;margin:12px 0}.hv2-zoom input{flex:1}.hv2-crop-help{text-align:center;font-size:12px;color:#888;margin:8px}.hv2-crop-panel>#hv2CropDone{width:100%;border:0;border-radius:15px;background:#262227;color:#fff;padding:13px;font-weight:800}`;document.head.appendChild(st);
new MutationObserver(install).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',async e=>{const b=e.target.closest?.('#hv2Save');if(!b)return;e.preventDefault();e.stopImmediatePropagation();b.disabled=true;b.textContent='保存中…';try{await save()}catch(err){console.error(err);alert(err?.message||'保存できなかったっしょ');b.disabled=false;b.textContent='保存'}},true);
})();