(()=>{
  const ACTIVE='oshiHomeActiveOshiId';
  const SETTINGS='oshiHomeSettingsByOshi';
  const TOOLBAR='oshiToolbarItems';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const list=()=>{try{return typeof oshis!=='undefined'&&Array.isArray(oshis)?oshis:(Array.isArray(window.oshis)?window.oshis:[])}catch{return[]}};
  function active(){const a=list(),id=localStorage.getItem(ACTIVE);return (id&&a.find(o=>String(o.id)===String(id)))||a.find(o=>o.favorite)||a[0]||null}
  function homes(){try{return JSON.parse(localStorage.getItem(SETTINGS)||'{}')}catch{return{}}}
  function cfg(o){const s=homes()[String(o.id)]||{};return{backgroundType:s.backgroundType||'image',backgroundData:s.backgroundData||o.icon||'',oshiIcon:s.oshiIcon||o.icon||'',oshiName:s.oshiName||o.name||'',fanIcon:s.fanIcon||'',fanName:s.fanName||'わたし',phrase:s.phrase||'好きになって',startDate:s.startDate||o.startDate||'',showDays:s.showDays!==false,showYmd:s.showYmd!==false,showBirthday:s.showBirthday!==false,textColor:s.textColor||'#fff',overlay:s.overlay==null?36:Number(s.overlay)}}
  function date(v){if(!v)return null;const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?null:d}
  function fmt(v){const d=date(v);return d?`${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`:''}
  function elapsed(v){const s=date(v);if(!s)return null;const n=new Date(),t=new Date(n.getFullYear(),n.getMonth(),n.getDate());let days=Math.max(0,Math.floor((t-s)/86400000));let y=t.getFullYear()-s.getFullYear(),m=t.getMonth()-s.getMonth(),d=t.getDate()-s.getDate();if(d<0){m--;d+=new Date(t.getFullYear(),t.getMonth(),0).getDate()}if(m<0){y--;m+=12}return{days,y:Math.max(0,y),m:Math.max(0,m),d:Math.max(0,d)}}
  function birth(o){if(o.birthDate)return fmt(o.birthDate);if(o.birthMonth&&o.birthDay)return`${String(o.birthMonth).padStart(2,'0')}.${String(o.birthDay).padStart(2,'0')}`;return''}
  function ensure(){if(document.getElementById('homeScreen'))return document.getElementById('homeScreen');const ls=document.getElementById('listScreen');if(!ls)return null;const s=document.createElement('section');s.id='homeScreen';s.className='screen';s.innerHTML='<div id="homeBody"></div>';ls.parentNode.insertBefore(s,ls);return s}
  function render(){const home=ensure(),body=document.getElementById('homeBody');if(!home||!body)return;const o=active();if(!o){body.innerHTML='<div class="homeEmpty"><div class="homeEmptyIcon">💘</div><b>まず推しを登録しよう</b><div class="sub">推し一覧から登録すると、ここが推しホームになるっしょ。</div></div>';return}const s=cfg(o),e=elapsed(s.startDate),bd=birth(o);const bg=s.backgroundData?(s.backgroundType==='video'?`<video class="homeFullMedia" src="${s.backgroundData}" autoplay muted loop playsinline></video>`:`<img class="homeFullMedia" src="${s.backgroundData}" alt="">`):`<div class="homeFallback" style="background:${esc(o.color||'#d86aa8')}"></div>`;body.innerHTML=`<div class="fanHome" style="--home-text:${esc(s.textColor)};--home-overlay:${Math.max(0,Math.min(80,s.overlay))/100}">${bg}<div class="fanHomeOverlay"></div><div class="fanHomeTop"><button type="button" class="homeRoundBtn" id="rescueOshiMenu">☰</button><button type="button" class="homeRoundBtn" id="rescueHomeEdit">✎</button></div><div class="fanHomeContent"><div class="peopleRow"><div class="personBlock"><div class="personAvatar">${s.oshiIcon?`<img src="${s.oshiIcon}">`:'💘'}</div><b>${esc(s.oshiName)}</b></div><div class="heartMark">♡</div><div class="personBlock"><div class="personAvatar fan">${s.fanIcon?`<img src="${s.fanIcon}">`:'☺︎'}</div><b>${esc(s.fanName)}</b></div></div><div class="phrase">${esc(s.phrase)}</div>${s.startDate?`<div class="startDate">${fmt(s.startDate)}</div>`:''}${e&&s.showDays?`<div class="daysCount">${e.days.toLocaleString('ja-JP')} <small>DAYS</small></div>`:''}${e&&s.showYmd?`<div class="ymdCount">${e.y}年 ${e.m}ヶ月 ${e.d}日</div>`:''}${s.showBirthday&&bd?`<div class="birthdayLine">🎂 ${esc(bd)}</div>`:''}</div></div>`;
    document.getElementById('rescueOshiMenu').onclick=()=>document.getElementById('homeOshiMenu')?.click();
    document.getElementById('rescueHomeEdit').onclick=()=>document.getElementById('homeEditBtn')?.click();
  }
  function rebuildToolbar(){const b=document.querySelector('.bottom');if(!b||b.children.length)return;const defs={schedule:['🗓','予定'],list:['💘','推し一覧'],home:['🏠','ホーム'],diary:['📖','日記'],menu:['☰','メニュー']};let items;try{items=JSON.parse(localStorage.getItem(TOOLBAR)||'null')}catch{}if(!Array.isArray(items)||!items.length)items=['schedule','list','home','diary','menu'];b.style.gridTemplateColumns=`repeat(${items.length},1fr)`;b.innerHTML=items.map(id=>`<button type="button" data-toolbar-id="${id}"><span>${defs[id]?.[0]||'•'}</span><small>${defs[id]?.[1]||id}</small></button>`).join('');b.querySelectorAll('[data-toolbar-id]').forEach(x=>x.onclick=()=>{const id=x.dataset.toolbarId;if(id==='home'){try{window.showHome?.()}catch{}setTimeout(render,0)}else if(id==='list')window.showList?.();else if(id==='menu')window.showSettings?.();else alert(id==='schedule'?'予定はこれから作るっしょ':'オタ活日記はこれから作るっしょ')})}
  setTimeout(()=>{rebuildToolbar();if(document.getElementById('homeScreen')?.classList.contains('active'))render()},260);
  window.addEventListener('pageshow',()=>{rebuildToolbar();if(document.getElementById('homeScreen')?.classList.contains('active'))render()});
  window.renderHomeSafe=render;
})();